name: setup
description: setup node and go for building

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6
      with:
        node-version: 25.2.1
        cache: npm
        cache-dependency-path: web/package-lock.json

    - name: install dependencies (web)
      working-directory: ./web
      run: npm ci
      shell: bash

    - name: build (web)
      working-directory: ./web
      run: npm run build
      shell: bash

    - name: rsync assets (web -> server)
      run: rsync -a --delete web/build/ server/router/assets/
      shell: bash

    - name: setup go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
