set shell := ["bash", "-uc"]

config_path := "../labstore.yml"

sandbox_bucket := "sandbox"

default:
    just -l

[working-directory: ".."]
check-deps:
    @echo "Checking system binary dependencies for backend..."
    @just check yq
    @just check mc
    @just check rclone
    @just check s5cmd

[group("helpers")]
print-mc-host:
    #!/bin/bash

    host=$(yq ".server.host" {{config_path}})
    port=$(yq ".server.port" {{config_path}})
    access_key=$(yq ".server.admin.access_key" {{config_path}})
    secret_key=$(yq ".server.admin.secret_key" {{config_path}})

    mc_host="http://${access_key}:${secret_key}@${host}:${port}"
    echo $mc_host

[group("helpers")]
print-rclone-config:
    #!/bin/bash

    HOST=$(yq ".server.host" {{config_path}})
    PORT=$(yq ".server.port" {{config_path}})
    ACCESS_KEY=$(yq ".server.admin.access_key" {{config_path}})
    SECRET_KEY=$(yq ".server.admin.secret_key" {{config_path}})

    cat <<EOF
    [local]
    type = s3
    provider = Other
    access_key_id = ${ACCESS_KEY}
    secret_access_key = ${SECRET_KEY}
    endpoint = http://${HOST}:${PORT}
    acl = private
    EOF

[group("helpers")]
create-bucket bucket: check-deps
    #!/bin/bash
    export MC_HOST_local=$(just print-mc-host)
    mc mb -p local/{{bucket}}

[group("helpers")]
sandbox-bucket:
    just create-bucket {{sandbox_bucket}}

[group("test-put")]
test-put-obj-mc: sandbox-bucket check-deps
    #!/bin/bash

    tmpfile=$(mktemp)
    export MC_HOST_local=$(just print-mc-host)

    echo "==> Generating temporary file with 10 MiB: $tmpfile"
    dd if=/dev/urandom of=$tmpfile bs=1M count=10

    echo "==> Sending temporary file: $tmpfile"
    mc cp --disable-multipart $tmpfile local/{{sandbox_bucket}}/$(basename $tmpfile).mc

    echo "==> Cleaning up temporary file: $tmpfile"
    rm -f $tmpfile

[group("test-put")]
test-put-obj-rclone: sandbox-bucket check-deps
    #!/bin/bash

    tmpfile=$(mktemp)

    echo "==> Generating temporary file with 10 MiB: $tmpfile"
    dd if=/dev/urandom of=$tmpfile bs=1M count=10
    tmpconfig=$(mktemp)

    echo "==> Creating temporary rclone config: $tmpconfig"
    just print-rclone-config >$tmpconfig

    echo "==> Sending temporary file: $tmpfile"
    rclone copyto $tmpfile local:/{{sandbox_bucket}}/$(basename $tmpfile).rclone --config $tmpconfig

    echo "==> Cleaning up temporary files: $tmpfile, $tmpconfig"
    rm -f $tmpfile $tmpconfig

[group("test-put")]
test-put-obj-s5cmd: sandbox-bucket check-deps
    #!/bin/bash

    tmpfile=$(mktemp)

    endpoint_url=$(just print-mc-host)

    export AWS_ACCESS_KEY_ID=$(yq ".server.admin.access_key" {{config_path}})
    export AWS_SECRET_ACCESS_KEY=$(yq ".server.admin.secret_key" {{config_path}})

    echo "==> Generating temporary file with 10 MiB: $tmpfile"
    dd if=/dev/urandom of=$tmpfile bs=1M count=10

    echo "==> Sending temporary file: $tmpfile"
    s5cmd --endpoint-url $endpoint_url cp $tmpfile s3://{{sandbox_bucket}}/$(basename $tmpfile).s5cmd

    echo "==> Cleaning up temporary file: $tmpfile"
    rm -f $tmpfile

[group("test-list")]
test-list-obj-mc: sandbox-bucket check-deps
    #!/bin/bash
    export MC_HOST_local=$(just print-mc-host)
    echo "==> Listing keys in {{sandbox_bucket}}"
    mc ls local/{{sandbox_bucket}}/

[group("test-list")]
test-list-obj-rclone: sandbox-bucket check-deps
    #!/bin/bash

    tmpconfig=$(mktemp)

    echo "==> Creating temporary rclone config: $tmpconfig"
    just print-rclone-config >$tmpconfig

    echo "==> Listing keys in {{sandbox_bucket}}"
    rclone lsf local:/{{sandbox_bucket}}/ --config $tmpconfig

    echo "==> Cleaning up temporary config: $tmpconfig"
    rm -f $tmpconfig

[group("test-list")]
test-list-obj-s5cmd: sandbox-bucket check-deps
    #!/bin/bash
    endpoint_url=$(just print-mc-host)

    export AWS_ACCESS_KEY_ID=$(yq ".server.admin.access_key" {{config_path}})
    export AWS_SECRET_ACCESS_KEY=$(yq ".server.admin.secret_key" {{config_path}})

    echo "==> Listing keys in {{sandbox_bucket}}"
    s5cmd --endpoint-url $endpoint_url ls s3://{{sandbox_bucket}}/
