set shell := ["bash", "-uc"]

config_path := "../labstore.yml"

test_bucket := "test-bucket"
test_user := "test_user"

default:
    just -l

[working-directory: ".."]
check-deps:
    @echo "Checking system binary dependencies for backend..."
    @just check yq
    @just check mc
    @just check rclone
    @just check s5cmd
    @just check http
    @just check sqlite3

[group("helpers")]
print-mc-host:
    #!/bin/bash

    host=$(yq ".backend.s3.server.host" {{config_path}})
    port=$(yq ".backend.s3.server.port" {{config_path}})
    access_key=$(yq ".backend.admin.auth.access_key" {{config_path}})
    secret_key=$(yq ".backend.admin.auth.secret_key" {{config_path}})

    mc_host="http://${access_key}:${secret_key}@${host}:${port}"
    echo $mc_host

[group("helpers")]
print-rclone-config:
    #!/bin/bash

    HOST=$(yq ".backend.s3.server.host" {{config_path}})
    PORT=$(yq ".backend.s3.server.port" {{config_path}})
    ACCESS_KEY=$(yq ".backend.admin.auth.access_key" {{config_path}})
    SECRET_KEY=$(yq ".backend.admin.auth.secret_key" {{config_path}})

    cat <<EOF
    [local]
    type = s3
    provider = Other
    access_key_id = ${ACCESS_KEY}
    secret_access_key = ${SECRET_KEY}
    endpoint = http://${HOST}:${PORT}
    acl = private
    EOF

[group("helpers")]
create-bucket bucket: check-deps
    #!/bin/bash
    export MC_HOST_local=$(just print-mc-host)
    mc mb -p local/{{bucket}}

[group("helpers")]
test-bucket:
    just create-bucket {{test_bucket}}

[group("test-put")]
test-put-obj-mc: test-bucket check-deps
    #!/bin/bash

    tmpfile=$(mktemp)
    export MC_HOST_local=$(just print-mc-host)

    echo "==> Generating temporary file with 10 MiB: $tmpfile"
    dd if=/dev/urandom of=$tmpfile bs=1M count=10

    echo "==> Sending temporary file: $tmpfile"
    mc cp --disable-multipart $tmpfile local/{{test_bucket}}/$(basename $tmpfile).mc

    echo "==> Cleaning up temporary file: $tmpfile"
    rm -f $tmpfile

[group("test-put")]
test-put-obj-rclone: test-bucket check-deps
    #!/bin/bash

    tmpfile=$(mktemp)

    echo "==> Generating temporary file with 10 MiB: $tmpfile"
    dd if=/dev/urandom of=$tmpfile bs=1M count=10
    tmpconfig=$(mktemp)

    echo "==> Creating temporary rclone config: $tmpconfig"
    just print-rclone-config >$tmpconfig

    echo "==> Sending temporary file: $tmpfile"
    rclone copyto $tmpfile local:/{{test_bucket}}/$(basename $tmpfile).rclone --config $tmpconfig

    echo "==> Cleaning up temporary files: $tmpfile, $tmpconfig"
    rm -f $tmpfile $tmpconfig

[group("test-put")]
test-put-obj-s5cmd: test-bucket check-deps
    #!/bin/bash

    tmpfile=$(mktemp)

    endpoint_url=$(just print-mc-host)

    export AWS_ACCESS_KEY_ID=$(yq ".backend.admin.auth.access_key" {{config_path}})
    export AWS_SECRET_ACCESS_KEY=$(yq ".backend.admin.auth.secret_key" {{config_path}})

    echo "==> Generating temporary file with 10 MiB: $tmpfile"
    dd if=/dev/urandom of=$tmpfile bs=1M count=10

    echo "==> Sending temporary file: $tmpfile"
    s5cmd --endpoint-url $endpoint_url cp $tmpfile s3://{{test_bucket}}/$(basename $tmpfile).s5cmd

    echo "==> Cleaning up temporary file: $tmpfile"
    rm -f $tmpfile

[group("test-list")]
test-list-obj-mc: test-bucket check-deps
    #!/bin/bash
    export MC_HOST_local=$(just print-mc-host)
    echo "==> Listing keys in {{test_bucket}}"
    mc ls local/{{test_bucket}}/

[group("test-list")]
test-list-obj-rclone: test-bucket check-deps
    #!/bin/bash

    tmpconfig=$(mktemp)

    echo "==> Creating temporary rclone config: $tmpconfig"
    just print-rclone-config >$tmpconfig

    echo "==> Listing keys in {{test_bucket}}"
    rclone lsf local:/{{test_bucket}}/ --config $tmpconfig

    echo "==> Cleaning up temporary config: $tmpconfig"
    rm -f $tmpconfig

[group("test-list")]
test-list-obj-s5cmd: test-bucket check-deps
    #!/bin/bash
    endpoint_url=$(just print-mc-host)

    export AWS_ACCESS_KEY_ID=$(yq ".backend.admin.auth.access_key" {{config_path}})
    export AWS_SECRET_ACCESS_KEY=$(yq ".backend.admin.auth.secret_key" {{config_path}})

    echo "==> Listing keys in {{test_bucket}}"
    s5cmd --endpoint-url $endpoint_url ls s3://{{test_bucket}}/

[group("test-iam")]
test-iam-create-user: check-deps
    #!/bin/bash
    echo "Creating IAM user: {{test_user}}"
    host=$(yq ".backend.iam.server.host" {{config_path}})
    port=$(yq ".backend.iam.server.port" {{config_path}})
    http POST "http://${host}:${port}?Action=CreateUser&UserName={{test_user}}"

[group("test-iam")]
test-iam-delete-user: check-deps
    #!/bin/bash
    echo "Deleting IAM user: {{test_user}}"
    iam_db=../$(yq ".backend.storage.data_dir" {{config_path}})/metadata/iam.db
    sqlite3 $iam_db "DELETE FROM users WHERE name = '{{test_user}}'"
