services:
  labstore-web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    ports:
      - 6790:6790
    environment:
      - S3_ENDPOINT=labstore-backend:${LS_PORT}
      - S3_ACCESS_KEY=${LS_ADMIN_ACCESS_KEY}
      - S3_SECRET_KEY=${LS_ADMIN_SECRET_KEY}
      - S3_REGION=eu-west-1
      - S3_USE_SSL=false
      - S3_FORCE_PATH_STYLE=true
    networks:
      - labstore
      - minio
    restart: unless-stopped

  labstore-backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    ports:
      - ${BENCHMARK_LABSTORE_PORT:-$LS_PORT}:${LS_PORT}
    environment:
      - LS_STORAGE_ROOT=/data
      - LS_HOST=${LS_HOST}
      - LS_PORT=${LS_PORT}
      - LS_ADMIN_ACCESS_KEY=${LS_ADMIN_ACCESS_KEY}
      - LS_ADMIN_SECRET_KEY=${LS_ADMIN_SECRET_KEY}
    volumes:
      - labstore:/data
    networks:
      - labstore
    command: serve
    restart: unless-stopped

  bench-minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - ${BENCHMARK_MINIO_PORT:-9000}:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${BENCHMARK_STORE_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${BENCHMARK_STORE_SECRET_KEY}
    volumes:
      - minio:/data
    networks:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
    restart: unless-stopped
    command: server /data --console-address ":9001"

  bench-garage:
    build:
      context: ..
      dockerfile: infra/Dockerfile.garage
    volumes:
      - garage:/var/lib/garage
    ports:
       - ${BENCHMARK_GARAGE_PORT:-3900}:3900
       - 3901:3901
       - 3902:3903
       - 3903:3903
    restart: unless-stopped

  bench-seaweedfs:
    image: chrislusf/seaweedfs:4.00
    volumes:
      - seaweedfs:/data
    ports:
      - 9333:9333
      - 8080:8080
      - 8888:8888
      - ${BENCHMARK_SEAWEEDFS_PORT:-8333}:8333
    environment:
      - AWS_ACCESS_KEY_ID=${BENCHMARK_STORE_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${BENCHMARK_STORE_SECRET_KEY}
    command: server -dir=/data -s3 -s3.port=8333
    restart: unless-stopped

  bench-rustfs:
    image: rustfs/rustfs:1.0.0-alpha.69
    volumes:
      - rustfs:/data
    ports:
      - ${BENCHMARK_RUSTFS_PORT:-10000}:9000
      - 10001:9001
    environment:
      - RUSTFS_ACCESS_KEY=${BENCHMARK_STORE_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${BENCHMARK_STORE_SECRET_KEY}
      - RUSTFS_CONSOLE_ENABLE=true
    restart: unless-stopped

  bench-iperf3-server:
    image: networkstatic/iperf3
    ports:
      - ${BENCHMARK_IPERF3_PORT:-5201}:5201/tcp
      - ${BENCHMARK_IPERF3_PORT:-5201}:5201/udp
    command: ["-s"]
    restart: unless-stopped

volumes:
  minio:
  labstore:
  garage:
  seaweedfs:
  rustfs:

networks:
  minio:
  labstore:
