[labstore-dev]
image=fedora-toolbox:latest
pull=true

additional_packages=git golang nodejs uv just docker-cli docker-compose sqlite3
additional_packages=golangci-lint pre-commit jq yq
additional_packages=rclone iperf3 nc

init_hooks=go install github.com/minio/mc@latest
init_hooks=go install github.com/peak/s5cmd/v2@master
init_hooks=go install github.com/minio/warp@latest
init_hooks=curl https://install.duckdb.org | sh
init_hooks=uv tool install termgraph==0.7.4
init_hooks=uv tool install --with=httpie-aws-authv4 httpie

# IMPORTANT: Change this to your own docker.sock path!
additional_flags=--volume /run/user/1000/podman/podman.sock:/var/run/docker.sock

# ======================
# OPTIONAL
# ======================

# --- fish ---
pre_init_hooks=export SHELL=/bin/fish
additional_packages=fish

# --- starfish ---
pre_init_hooks=dnf copr enable -y atim/starship
additional_packages=starship

# --- neovim ---
additional_packages=neovim
init_hooks=alternatives --install /usr/bin/vim vim /usr/bin/nvim 100

# --- lazygit ---
pre_init_hooks=dnf copr enable -y dejan/lazygit
additional_packages=lazygit

# --- lazydocker ---
init_hooks=go install github.com/jesseduffield/lazydocker@latest

# -- other ---
additional_packages=btop zoxide bat ripgrep fd-find direnv
