[labstore-dev]
image=fedora-toolbox:latest
pull=true

additional_packages=git golang nodejs uv just docker-cli sqlite3
additional_packages=golangci-lint pre-commit jq yq
additional_packages=rclone iperf3

init_hooks=go install github.com/minio/mc@latest
init_hooks=go install github.com/peak/s5cmd/v2@master
init_hooks=go install github.com/minio/warp@latest
init_hooks=curl https://install.duckdb.org | sh
init_hooks=uv tool install termgraph==0.7.4

# IMPORTANT: Change this to your own docker.sock path!
additional_flags=--volume /run/user/1000/podman/podman.sock:/var/run/docker.sock

# ======================
# OPTIONAL
# ======================

# --- Fish ---
pre_init_hooks=export SHELL=/bin/fish
additional_packages=fish

# --- Starfish ---
pre_init_hooks=dnf copr enable -y atim/starship
additional_packages=starship
