# =================
# Go builder
# =================

FROM --platform=$BUILDPLATFORM golang:1.25-alpine3.22 AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /labstore/backend

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend .

RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o bin/labstore-server ./cmd/labstore-server

# =================
# LabStore backend
# =================

FROM alpine:3.22

COPY --from=builder /labstore/backend/bin/labstore-server /usr/local/bin/labstore-server

RUN addgroup -S labstore && adduser -S labstore -G labstore

RUN mkdir /data
RUN chown -R labstore:labstore /data

VOLUME /data

USER labstore

ENTRYPOINT ["labstore-server"]
