set shell := ["bash", "-uc"]

set dotenv-load
set dotenv-required
set dotenv-path := "../.env"

default:
    just -l

[working-directory: ".."]
check-deps:
    @echo "Checking system binary dependencies for infra..."
    @just check docker

[group("provisioning")]
[working-directory: ".."]
up: check-deps
    docker compose -p labstore -f infra/compose.yml up --build -d

[group("provisioning")]
[working-directory: ".."]
down: check-deps
    docker compose -p labstore -f infra/compose.yml down -v
