set shell := ["bash", "-uc"]

export GIT_TAG := `git describe --tags --abbrev=0 2>/dev/null`
export GIT_COMMIT := `git rev-parse --short HEAD`

default:
    just -l

[working-directory: ".."]
check-deps:
    @echo "Checking system binary dependencies for infra..."
    @just check docker

[group("labstore")]
[working-directory: ".."]
up: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile labstore up --build -d

[group("labstore")]
[working-directory: ".."]
down: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile labstore down -v

[group("testing")]
[working-directory: ".."]
testing-up: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile testing up --build -d

[group("testing")]
[working-directory: ".."]
testing-down: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile testing down -v

[group("benchmark")]
[working-directory: ".."]
benchmark-up: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile benchmark up --build -d

[group("benchmark")]
[working-directory: ".."]
benchmark-down: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile benchmark down -v

[working-directory: ".."]
all-up: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile all up --build -d

[working-directory: ".."]
all-down: check-deps
    #!/bin/bash
    eval $(just print-env)
    docker compose -p labstore -f infra/compose.yml --profile all down -v
