name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'testing-*'
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            goarch: arm
            goarm: 7

    steps:
      - uses: actions/checkout@v6

      - name: setup
        uses: ./.github/actions/setup

      - name: set binary name
        id: binary
        run: |
          BIN="labstore-${{ github.ref_name }}"
          BIN="${BIN}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm && format('v{0}', matrix.goarm) }}"
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN="${BIN}.exe"
          echo "name=$BIN" >> $GITHUB_OUTPUT

      - name: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist

          if [ -n "${{ matrix.goarm }}" ]; then
            export GOARM=${{ matrix.goarm }}
          fi

          go build -o dist/${{ steps.binary.outputs.name }} ./cli/cmd/labstore

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          includeRefIssues: true
          writeToFile: false

      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.ref_name }}
          name: Release ${{ github.event.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
