name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'testing-*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            goarch: arm
            goarm: 7

    steps:
      - uses: actions/checkout@v6

      - name: setup
        uses: ./.github/actions/setup

      - name: set binary name
        id: binary
        run: |
          BIN="labstore-${{ github.ref_name }}"
          BIN="${BIN}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm && format('v{0}', matrix.goarm) }}"
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN="${BIN}.exe"
          echo "Binary: $BIN"
          echo "name=$BIN" >> $GITHUB_OUTPUT

      - name: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: |
          mkdir -p dist
          GO_CONSTANTS="github.com/IllumiKnowLabs/labstore/server/constants"
          LDFLAGS="-X ${GO_CONSTANTS}.GitTag=$(git describe --tags --abbrev=0 2>/dev/null) \
            -X ${GO_CONSTANTS}.GitCommit=$(git rev-parse --short HEAD) \
            -X ${GO_CONSTANTS}.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
            -X ${GO_CONSTANTS}.Builder=release-gha"
          go build -tags embedassets -ldflags "$LDFLAGS" -o dist/${{ steps.binary.outputs.name }} ./cmd/labstore

      - name: upload artifacts (binaries)
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.binary.outputs.name }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup
        uses: ./.github/actions/setup

      - name: download artifacts (binaries)
        uses: actions/download-artifact@v7
        with:
          path: dist/

      - name: zip assets (web)
        run: |
          mkdir -p assets dist
          cp -R web/build/* assets/
          zip -r dist/assets.zip assets/

      - name: generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          includeRefIssues: false
          writeToFile: false

      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
