name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "release/**"

permissions:
  contents: read

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: install dependencies
        working-directory: ./backend
        run: go mod download

      - name: go test
        working-directory: ./backend
        run: go test -v ./...
