name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: install dependencies
        run: go mod download

      - name: go test
        run: go test -v ./...
