name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "release/**"

permissions:
  contents: read

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 25.2.1
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: install dependencies (web)
        working-directory: ./web
        run: npm ci

      - name: build (web)
        working-directory: ./web
        run: npm run build

      - name: rsync assets (web -> server)
        run: rsync -a --delete web/build/ server/pkg/router/assets/

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/*.sum"

      - name: go test (server)
        run: go test -v ./server/...

      - name: go test (client)
        run: go test -v ./client/...

      - name: go test (cli)
        run: go test -v ./cli/...
